services:

  db:
    image: postgres:16-alpine
    container_name: ai-bill-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: bill_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d bill_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - ai-bill-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ai-bill-backend

    restart: unless-stopped

    env_file:
      - backend/.env

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/bill_ai

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/exports:/app/exports

    networks:
      - ai-bill-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://13.233.146.28:8000/api/v1

    container_name: ai-bill-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"

    networks:
      - ai-bill-network


volumes:
  postgres_data:


networks:
  ai-bill-network:
    driver: bridge
