"""create invoices table

Revision ID: 7907c2a16886
Revises: 45d18f4942b3
Create Date: 2026-07-09 15:11:02.017875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7907c2a16886'
down_revision: Union[str, Sequence[str], None] = '45d18f4942b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'AI_PROCESSING', 'AI_COMPLETED', 'REVIEWED', 'EXPORTED', name='invoicestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
