"""add gst verification fields

Revision ID: ae5f79177af3
Revises: 7907c2a16886
Create Date: 2026-07-09 21:39:14.163145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5f79177af3'
down_revision: Union[str, Sequence[str], None] = '7907c2a16886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('gst_match', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('verification_message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'verification_message')
    op.drop_column('invoices', 'gst_match')
    # ### end Alembic commands ###
